version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - corepack enable
            - corepack prepare pnpm@latest --activate
            - pnpm config set store-dir .pnpm-store
            - pnpm install
        build:
          commands:
            - pnpm --filter towfleet-web build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - .pnpm-store/**
          - .next/cache/**/*
    appRoot: apps/towfleet-web
