/**
 * Curated Lucide icon set (spec §10.10 — one consistent stroke family).
 * Import icons from here, never directly from lucide-react-native, so the
 * family can be swapped in one place.
 */
export {
  Menu,
  Bell,
  MapPin,
  LocateFixed,
  Navigation,
  ArrowLeft,
  ArrowUpDown,
  ChevronDown,
  ChevronRight,
  Info,
  // §9.1.5's surge badge (Phase 14). The curated set had no
  // demand/intensity glyph — this is the family's own trend icon.
  TrendingUp,
  Check,
  StickyNote,
  Plus,
  Heart,
  History,
  X,
  CircleX,
  CircleCheck,
  RefreshCw,
  Phone,
  MessageCircle,
  Star,
  Truck,
  Bike,
  Calendar,
  Clock,
  CalendarClock,
  BatteryCharging,
  LifeBuoy,
  Fuel,
  Lock,
  Cable,
  ShieldCheck,
  Headphones,
  Home,
  ClipboardList,
  Wrench,
  User,
  CarFront,
  CreditCard,
  CircleHelp,
  Settings,
  LogOut,
  Mail,
  Camera,
  Trash2,
  Briefcase,
  Wallet,
  Search,
  Pencil,
  FileText,
  Globe,
  Palette,
  Receipt,
  Route,
  IndianRupee,
  WifiOff,
  Download,
  // Phase 18 (§9.1.7 live tracking): the share sheet, the arrival cue, and
  // the §11.6 support banner.
  Share2,
  TriangleAlert,
  Copy,
} from 'lucide-react-native';
