import type { ImageSourcePropType } from 'react-native';

/**
 * Every Figma colour icon (icon/color/*, holder frame 323:4357 "Icons · colour (Ehsan)")
 * as a transparent 192×192 PNG (48pt square at 4×, art centred with the component's own
 * margin, all four corners alpha 0) in `src/assets/icons/mi-<name>.png`.
 *
 * Key = the Figma name after `icon/color/`. Render with `<MiColorIcon name="..." size={..} />`.
 */
export const colorIconSources = {
  'add-photo': require('../../assets/icons/mi-add-photo.png'),
  'add-stop': require('../../assets/icons/mi-add-stop.png'),
  alert: require('../../assets/icons/mi-alert.png'),
  ambulance: require('../../assets/icons/mi-ambulance.png'),
  appearance: require('../../assets/icons/mi-appearance.png'),
  battery: require('../../assets/icons/mi-battery.png'),
  'bell-off': require('../../assets/icons/mi-bell-off.png'),
  bell: require('../../assets/icons/mi-bell.png'),
  bike: require('../../assets/icons/mi-bike.png'),
  bolt: require('../../assets/icons/mi-bolt.png'),
  briefcase: require('../../assets/icons/mi-briefcase.png'),
  calendar: require('../../assets/icons/mi-calendar.png'),
  call: require('../../assets/icons/mi-call.png'),
  camera: require('../../assets/icons/mi-camera.png'),
  car: require('../../assets/icons/mi-car.png'),
  card: require('../../assets/icons/mi-card.png'),
  cash: require('../../assets/icons/mi-cash.png'),
  chat: require('../../assets/icons/mi-chat.png'),
  clock: require('../../assets/icons/mi-clock.png'),
  'contact-alert': require('../../assets/icons/mi-contact-alert.png'),
  copy: require('../../assets/icons/mi-copy.png'),
  device: require('../../assets/icons/mi-device.png'),
  document: require('../../assets/icons/mi-document.png'),
  download: require('../../assets/icons/mi-download.png'),
  faq: require('../../assets/icons/mi-faq.png'),
  feedback: require('../../assets/icons/mi-feedback.png'),
  fire: require('../../assets/icons/mi-fire.png'),
  'free-cancel': require('../../assets/icons/mi-free-cancel.png'),
  'fuel-pump': require('../../assets/icons/mi-fuel-pump.png'),
  gift: require('../../assets/icons/mi-gift.png'),
  globe: require('../../assets/icons/mi-globe.png'),
  help: require('../../assets/icons/mi-help.png'),
  home: require('../../assets/icons/mi-home.png'),
  hourglass: require('../../assets/icons/mi-hourglass.png'),
  info: require('../../assets/icons/mi-info.png'),
  'jerry-can': require('../../assets/icons/mi-jerry-can.png'),
  lightbulb: require('../../assets/icons/mi-lightbulb.png'),
  lock: require('../../assets/icons/mi-lock.png'),
  'log-out': require('../../assets/icons/mi-log-out.png'),
  map: require('../../assets/icons/mi-map.png'),
  moon: require('../../assets/icons/mi-moon.png'),
  payment: require('../../assets/icons/mi-payment.png'),
  place: require('../../assets/icons/mi-place.png'),
  'plus-badge': require('../../assets/icons/mi-plus-badge.png'),
  plus: require('../../assets/icons/mi-plus.png'),
  police: require('../../assets/icons/mi-police.png'),
  receipt: require('../../assets/icons/mi-receipt.png'),
  recent: require('../../assets/icons/mi-recent.png'),
  refer: require('../../assets/icons/mi-refer.png'),
  refund: require('../../assets/icons/mi-refund.png'),
  'report-issue': require('../../assets/icons/mi-report-issue.png'),
  search: require('../../assets/icons/mi-search.png'),
  settings: require('../../assets/icons/mi-settings.png'),
  siren: require('../../assets/icons/mi-siren.png'),
  sun: require('../../assets/icons/mi-sun.png'),
  suv: require('../../assets/icons/mi-suv.png'),
  swap: require('../../assets/icons/mi-swap.png'),
  tag: require('../../assets/icons/mi-tag.png'),
  'tow-truck': require('../../assets/icons/mi-tow-truck.png'),
  'trash-red': require('../../assets/icons/mi-trash-red.png'),
  trash: require('../../assets/icons/mi-trash.png'),
  tyre: require('../../assets/icons/mi-tyre.png'),
  upi: require('../../assets/icons/mi-upi.png'),
  upload: require('../../assets/icons/mi-upload.png'),
  'user-plus': require('../../assets/icons/mi-user-plus.png'),
  'user-shield': require('../../assets/icons/mi-user-shield.png'),
  user: require('../../assets/icons/mi-user.png'),
  verified: require('../../assets/icons/mi-verified.png'),
  wallet: require('../../assets/icons/mi-wallet.png'),
  wrench: require('../../assets/icons/mi-wrench.png'),
} as const satisfies Record<string, ImageSourcePropType>;

export type MiColorIconName = keyof typeof colorIconSources;
